/**
 * HOBBIX - Tabletop & Hobby Games Store
 * Catalog Database & Global Product Repository
 */

const STORE_DATA = {
  products: [
    {
      id: "prod-1",
      title: "Frosthaven: Legends of the North",
      category: "Strategy",
      categoryKey: "strategy",
      price: 159.99,
      originalPrice: 189.99,
      discount: "-15%",
      badge: "Game of Week",
      rating: 4.9,
      reviews: 328,
      players: "1-4 Players",
      playerMin: 1,
      playerMax: 4,
      playerBucket: "1-2",
      age: "14+",
      ageNum: 14,
      time: "90-180 Min",
      difficulty: "Expert",
      inStock: true,
      featured: true,
      bestseller: true,
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80",
      description: "The massive standalone fantasy dungeon crawler campaign. Build up a frostbound outpost, craft alchemical weapons, and delve into over 100 deep tactical scenarios."
    },
    {
      id: "prod-2",
      title: "Dune: Imperium – Uprising",
      category: "Strategy",
      categoryKey: "strategy",
      price: 64.99,
      originalPrice: 74.99,
      discount: "-13%",
      badge: "Hot Choice",
      rating: 4.95,
      reviews: 412,
      players: "1-4 Players",
      playerMin: 1,
      playerMax: 4,
      playerBucket: "3-4",
      age: "14+",
      ageNum: 14,
      time: "60-120 Min",
      difficulty: "Medium",
      inStock: true,
      featured: true,
      bestseller: true,
      image: "asstes/Dune Imperium – Uprising.jpg",
      description: "A masterful fusion of deck-building and worker placement on the desert sands of Arrakis. Command sandworms and harness political intrigue."
    },
    {
      id: "prod-3",
      title: "Wingspan: Master Collector's Edition",
      category: "Family",
      categoryKey: "family",
      price: 59.99,
      originalPrice: 69.99,
      discount: "-14%",
      badge: "Award Winner",
      rating: 4.85,
      reviews: 890,
      players: "1-5 Players",
      playerMin: 1,
      playerMax: 5,
      playerBucket: "3-4",
      age: "10+",
      ageNum: 10,
      time: "40-70 Min",
      difficulty: "Medium",
      inStock: true,
      featured: true,
      bestseller: true,
      image: "asstes/Wingspan Master Collector's Edition.jpg",
      description: "A relaxing, competitive engine-building board game all about attracting a stunning menagerie of birds to your wildlife preserve."
    },
    {
      id: "prod-4",
      title: "Arkham Horror: The Living Card Game",
      category: "Card",
      categoryKey: "card",
      price: 47.99,
      originalPrice: 59.99,
      discount: "-20%",
      badge: "Co-op Classic",
      rating: 4.9,
      reviews: 530,
      players: "1-2 Players",
      playerMin: 1,
      playerMax: 2,
      playerBucket: "1-2",
      age: "14+",
      ageNum: 14,
      time: "45-90 Min",
      difficulty: "Expert",
      inStock: true,
      featured: false,
      bestseller: true,
      image: "asstes/Arkham Horror The Living Card Game.jpg",
      description: "Step into 1920s Massachusetts and fight eldritch cosmic terrors in this acclaimed living card campaign game."
    },
    {
      id: "prod-5",
      title: "Secret Hitler: Deluxe Wooden Box Edition",
      category: "Family",
      categoryKey: "family",
      price: 39.99,
      originalPrice: 45.00,
      discount: "-11%",
      badge: "Party Hit",
      rating: 4.8,
      reviews: 640,
      players: "5-10 Players",
      playerMin: 5,
      playerMax: 10,
      playerBucket: "5+",
      age: "14+",
      ageNum: 14,
      time: "30-45 Min",
      difficulty: "Beginner",
      inStock: true,
      featured: true,
      bestseller: true,
      image: "asstes/Secret Hitler Deluxe Wooden Box Edition.jpg",
      description: "A dramatic social deduction game of political betrayal and deception set in 1930s Germany. Find liberals, uncover fascists."
    },
    {
      id: "prod-6",
      title: "Cascadia: Pacific Northwest Wonders",
      category: "Puzzle",
      categoryKey: "puzzle",
      price: 34.99,
      originalPrice: 42.00,
      discount: "-17%",
      badge: "Spiel des Jahres",
      rating: 4.9,
      reviews: 720,
      players: "1-4 Players",
      playerMin: 1,
      playerMax: 4,
      playerBucket: "1-2",
      age: "10+",
      ageNum: 10,
      time: "30-45 Min",
      difficulty: "Beginner",
      inStock: true,
      featured: false,
      bestseller: true,
      image: "asstes/Cascadia Pacific Northwest Wonders.jpg",
      description: "Draft habitat tiles and wildlife tokens to build the most harmonious ecosystem in this soothing, clever spatial puzzle game."
    },
    {
      id: "prod-7",
      title: "Dungeons & Dragons 2024 Player's Handbook",
      category: "RPG",
      categoryKey: "rpg",
      price: 49.99,
      originalPrice: 59.99,
      discount: "-16%",
      badge: "New Edition",
      rating: 4.95,
      reviews: 950,
      players: "2-8 Players",
      playerMin: 2,
      playerMax: 8,
      playerBucket: "5+",
      age: "12+",
      ageNum: 12,
      time: "120-240 Min",
      difficulty: "Medium",
      inStock: true,
      featured: true,
      bestseller: true,
      image: "asstes/Dungeons & Dragons 2024 Player's Handbook.jpg",
      description: "The quintessential tabletop RPG guidebook reimagined with overhauled class progression, spells, feat trees, and glorious art."
    },
    {
      id: "prod-8",
      title: "Mythic Prismatic Metal Polyhedral Dice Set",
      category: "Accessories",
      categoryKey: "accessories",
      price: 28.50,
      originalPrice: 35.00,
      discount: "-18%",
      badge: "Handcrafted",
      rating: 4.9,
      reviews: 310,
      players: "All Tabletop",
      playerMin: 1,
      playerMax: 10,
      playerBucket: "1-2",
      age: "8+",
      ageNum: 8,
      time: "Lifetime",
      difficulty: "Beginner",
      inStock: true,
      featured: false,
      bestseller: true,
      image: "asstes/Mythic Prismatic Metal Polyhedral Dice Set.jpg",
      description: "Heavyweight zinc-alloy 7-piece polyhedral dice with chromatic prism plating and engraved dragon rune numerals."
    },
    {
      id: "prod-9",
      title: "Root: A Game of Woodland Might and Right",
      category: "Strategy",
      categoryKey: "strategy",
      price: 54.99,
      originalPrice: 60.00,
      discount: "-8%",
      badge: "Asymmetric",
      rating: 4.85,
      reviews: 480,
      players: "2-4 Players",
      playerMin: 2,
      playerMax: 4,
      playerBucket: "3-4",
      age: "14+",
      ageNum: 14,
      time: "60-90 Min",
      difficulty: "Expert",
      inStock: true,
      featured: false,
      bestseller: false,
      image: "asstes/Root A Game of Woodland Might and Right.jpg",
      description: "A breathtaking game of woodland asymmetric warfare. Play as Marquise de Cat, the Eyrie Dynasties, the Woodland Alliance, or the Vagabond."
    },
    {
      id: "prod-10",
      title: "Codenames: Duet Deluxe Edition",
      category: "Card",
      categoryKey: "card",
      price: 24.99,
      originalPrice: 29.99,
      discount: "-16%",
      badge: "2-Player King",
      rating: 4.8,
      reviews: 580,
      players: "2 Players",
      playerMin: 2,
      playerMax: 2,
      playerBucket: "1-2",
      age: "10+",
      ageNum: 10,
      time: "15-30 Min",
      difficulty: "Beginner",
      inStock: true,
      featured: false,
      bestseller: true,
      image: "asstes/Codenames Duet Deluxe Edition.jpg",
      description: "The award-winning cooperative word game designed specifically for pairs. Give one-word clues to uncover secret agents before time runs out."
    },
    {
      id: "prod-11",
      title: "Azul: Master Chocolatier Special Edition",
      category: "Puzzle",
      categoryKey: "puzzle",
      price: 44.99,
      originalPrice: 49.99,
      discount: "-10%",
      badge: "Sensory Delight",
      rating: 4.88,
      reviews: 490,
      players: "2-4 Players",
      playerMin: 2,
      playerMax: 4,
      playerBucket: "3-4",
      age: "8+",
      ageNum: 8,
      time: "30-45 Min",
      difficulty: "Beginner",
      inStock: true,
      featured: false,
      bestseller: true,
      image: "asstes/Azul Master Chocolatier Special Edition.jpg",
      description: "Draft gorgeous mosaic tiles in a race to craft the most magnificent palace facade while avoiding wasted pieces."
    },
    {
      id: "prod-12",
      title: "Call of Cthulhu: Keeper Rulebook (7th Ed)",
      category: "RPG",
      categoryKey: "rpg",
      price: 52.00,
      originalPrice: 59.99,
      discount: "-13%",
      badge: "Horror TTRPG",
      rating: 4.92,
      reviews: 340,
      players: "2-6 Players",
      playerMin: 2,
      playerMax: 6,
      playerBucket: "5+",
      age: "16+",
      ageNum: 16,
      time: "120-180 Min",
      difficulty: "Medium",
      inStock: true,
      featured: false,
      bestseller: false,
      image: "asstes/Call of Cthulhu Keeper Rulebook.jpg",
      description: "The quintessential horror roleplaying game of mystery and cosmic madness. Guide investigators through shadowy occult secrets."
    },
    {
      id: "prod-13",
      title: "The Crew: Mission Deep Sea",
      category: "Card",
      categoryKey: "card",
      price: 14.99,
      originalPrice: 18.00,
      discount: "-16%",
      badge: "Pocket Gem",
      rating: 4.9,
      reviews: 620,
      players: "2-5 Players",
      playerMin: 2,
      playerMax: 5,
      playerBucket: "3-4",
      age: "10+",
      ageNum: 10,
      time: "20-30 Min",
      difficulty: "Medium",
      inStock: true,
      featured: false,
      bestseller: true,
      image: "asstes/The Crew Mission Deep Sea.jpg",
      description: "A gripping cooperative trick-taking adventure with 96 unique deep-sea missions and limited communication mechanics."
    },
    {
      id: "prod-14",
      title: "Neoprene Heavy-Duty Tabletop Playmat (6x3 ft)",
      category: "Accessories",
      categoryKey: "accessories",
      price: 79.99,
      originalPrice: 95.00,
      discount: "-15%",
      badge: "Premium Gear",
      rating: 4.95,
      reviews: 215,
      players: "All Formats",
      playerMin: 1,
      playerMax: 8,
      playerBucket: "1-2",
      age: "All Ages",
      ageNum: 0,
      time: "Endless",
      difficulty: "Beginner",
      inStock: true,
      featured: false,
      bestseller: false,
      image: "asstes/Neoprene Tabletop Playmat.jpg",
      description: "Stitched-edge, 4mm thick rubberized neoprene playmat with cosmic starfield print and anti-slip water-resistant backing."
    },
    {
      id: "prod-15",
      title: "Terraforming Mars: Big Box Collector Bundle",
      category: "Strategy",
      categoryKey: "strategy",
      price: 139.99,
      originalPrice: 160.00,
      discount: "-12%",
      badge: "Top 5 BGG",
      rating: 4.94,
      reviews: 880,
      players: "1-5 Players",
      playerMin: 1,
      playerMax: 5,
      playerBucket: "3-4",
      age: "12+",
      ageNum: 12,
      time: "90-150 Min",
      difficulty: "Expert",
      inStock: true,
      featured: false,
      bestseller: true,
      image: "asstes/Terraforming Mars Big Box.jpg",
      description: "Transform the Red Planet with 3D terrain tiles, metal resource markers, and corporations competing for interplanetary dominance."
    }
  ],

  events: [
    {
      id: "evt-1",
      title: "Friday Night Commander & D&D Tavern Crawl",
      game: "Magic: The Gathering & D&D 5e",
      day: "28",
      month: "AUG",
      time: "6:30 PM - 10:30 PM",
      host: "Grand Master Vance",
      seatsTotal: 24,
      seatsLeft: 4,
      fee: "Free with Drink Purchase",
      location: "Main Tavern Hall & Private Booths",
      image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80",
      desc: "Casual EDH pods and one-shot beginner D&D adventures. Dice trays and loaner decks available!"
    },
    {
      id: "evt-2",
      title: "Catan Championship Qualifier 2026",
      game: "Settlers of Catan",
      day: "04",
      month: "SEP",
      time: "1:00 PM - 7:00 PM",
      host: "Judge Andrea Cole",
      seatsTotal: 32,
      seatsLeft: 8,
      fee: "$15 Entry (Prize Pool $500)",
      location: "Grand Tournament Arena",
      image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=800&q=80",
      desc: "Official regional qualifier. Top 4 players receive custom wooden trophy boards and exclusive promo cards."
    },
    {
      id: "evt-3",
      title: "Heavy Strategy Sunday: Dune & Brass",
      game: "Dune: Imperium & Brass Birmingham",
      day: "07",
      month: "SEP",
      time: "12:00 PM - 6:00 PM",
      host: "Strategist Marcus",
      seatsTotal: 16,
      seatsLeft: 2,
      fee: "Free Entry",
      location: "Strategist Vault Lounge",
      image: "asstes/Dune Imperium – Uprising.jpg",
      desc: "Dedicated to mid-to-heavyweight Euro and engine builders. Full rules teaching provided at table start."
    },
    {
      id: "evt-4",
      title: "Warhammer 40k & Miniatures Painting Clinic",
      game: "Warhammer 40k / Miniature Art",
      day: "12",
      month: "SEP",
      time: "4:00 PM - 8:00 PM",
      host: "Artisan Elena Vance",
      seatsTotal: 12,
      seatsLeft: 5,
      fee: "$10 (Includes mini & Citadel paints)",
      location: "Workshop Craft Studio",
      image: "https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=800&q=80",
      desc: "Master wet blending, dry brushing, and edge highlighting with pro-level hobbyist guidance."
    }
  ],

  articles: [
    {
      id: "art-1",
      title: "Top 10 Heavyweight Board Games of 2026: The Strategic Masterpieces",
      category: "Game Reviews",
      date: "August 24, 2026",
      readTime: "7 Min Read",
      author: "Julian Thorne",
      authorRole: "Senior Tabletop Strategist · 400+ Logged Plays",
      authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
      authorBio: "Julian has managed tournament ladders and curated heavy Euro acquisitions for Hobbix since 2019. When he isn't crunching supply chain graphs in Brass: Birmingham, he hosts Friday Demo Nights at our Seattle Flagship lounge.",
      authorFavs: "Brass: Birmingham • Dune: Imperium • Terraforming Mars • Arkham Horror",
      image: "asstes/Dune Imperium – Uprising.jpg",
      caption: "Strategic worker-placement and deckbuilding in Dune: Imperium – Uprising at the Hobbix Seattle Flagship Lounge.",
      excerpt: "From complex resource optimization in deep space to industrial revolution economics and frozen tactical campaigns, we break down the definitive heavyweight board games you must experience this year.",
      tags: ["HeavyEuro", "BrassBirmingham", "DuneImperium", "Strategy2026"],
      featuredProducts: ["prod-1", "prod-2"],
      leadProse: "The modern board gaming landscape has evolved far beyond simple roll-and-move mechanics. Today’s heavyweight tabletop games are intricate clocks of interlocking decisions, unforgiving economic tension, and deeply rewarding multi-layered strategies. In 2026, designers have pushed the boundaries of worker placement, hand management, and spatial logistics to unprecedented heights.",
      pullQuote: {
        quote: "In a true heavyweight masterpiece, victory isn't determined by lucky dice rolls—it is forged in tight supply chains, brutal timing, and outmaneuvering your rivals at the margins.",
        cite: "Julian Thorne, Head Tabletop Curator"
      },
      specCard: {
        title: "Brass: Birmingham Deluxe",
        badge: "Top Pick #1",
        rating: "9.8",
        weight: "4.4 / 5.0 (Heavy)",
        players: "2–4 Players (Best at 3-4)",
        time: "120–180 Minutes",
        mechanics: "Network Building, Loans, Hand Mgmt",
        pros: [
          "Peerless interconnected economy—using opponent's beer and coal creates immense table interaction.",
          "Dual-era transition (Canal to Rail) completely shifts board geography at mid-game.",
          "Cast iron clay chips and linen-finish boards provide sublime tactile luxury."
        ]
      },
      secondaryImages: [
        { src: "asstes/Arkham Horror The Living Card Game.jpg", tag: "Campaign Narrative Depth" },
        { src: "asstes/Wingspan Master Collector's Edition.jpg", tag: "Precision Engine Building" }
      ],
      tactics: [
        { num: "01", title: "Track Tempo & Turn Economy", desc: "In engine-builders like Arkham Horror or Dune, actions are your rarest currency. Prioritize moves that generate compound action efficiency over one-off victory points early on." },
        { num: "02", title: "Embrace Flexible Specialization", desc: "Never lock yourself into a single scoring pathway before Round 2. Observe what spaces your opponents neglect and capitalize on undervalued board resources." },
        { num: "03", title: "Manage Table Heat & Threat Posture", desc: "Racing to a commanding lead in Round 1 paints a target on your back. Keep your scoring engines veiled and detonate big scoring combos in the penultimate round." },
        { num: "04", title: "Sleeve & Organize for Fast Pacing", desc: "Heavy games flow 30% faster when tokens are sorted in magnetic trays and cards are sleeved with matte textures for lightning-fast shuffles." }
      ],
      comments: [
        { name: "David K.", badge: "Verified Buyer", date: "August 25, 2026 • 3:14 PM", stars: 5, text: "Completely agree with the #1 spot for Brass: Birmingham. The beer economy completely fixes the runaway leader problem that older economic games had. Every single game comes down to a 3-point margin!" },
        { name: "Julian Thorne", badge: "Staff Curator", isStaff: true, date: "August 25, 2026 • 4:20 PM", text: "Spot on, David! That beer scarcity in the Rail Era forces players to build mutual infrastructure or pay heavy iron costs. Try an early pottery play in Uttoxeter next time!" },
        { name: "Sarah Chen", badge: "Lounge Member", date: "August 26, 2026 • 11:05 AM", stars: 5, text: "Dune: Imperium Uprising was the best board game purchase I made this year. The 6-player Commander mode is chaotic in the best way possible. Fast shipping to Portland too!" }
      ]
    },
    {
      id: "art-2",
      title: "The Ultimate Guide to Sleeving & Preserving Your Board Game Collection",
      category: "Hobby Guides",
      date: "August 20, 2026",
      readTime: "5 Min Read",
      author: "Sara Lin",
      authorRole: "Hobby Restoration & Archive Specialist",
      authorAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
      authorBio: "Sara has cataloged and archival-sleeved over 2,000 board game titles. She specializes in acid-free storage, custom 3D insert design, and corner preservation techniques.",
      authorFavs: "Wingspan • Cascadia • Everdell • Ark Nova",
      image: "asstes/Wingspan Master Collector's Edition.jpg",
      caption: "Precision 100-micron matte sleeves and archival token organizers on Wingspan Master Collector's Edition.",
      excerpt: "Standard vs matte, premium thickness microns, custom box inserts, and humidity control tips to keep your rare collector games pristine for decades.",
      tags: ["CardSleeving", "BoardGameCare", "CollectorTips", "Wingspan"],
      featuredProducts: ["prod-5", "prod-8"],
      leadProse: "When you invest in limited edition board games, maintaining pristine card edges, crisp rulebooks, and undamaged punchboards is both an art and a science. Micro-abrasions from shuffling, ambient humidity, and corner friction can degrade a collector's title within a single gaming season if left unprotected.",
      pullQuote: {
        quote: "Sleeving isn't just about protection—it transforms shuffling from a sluggish chore into a silky, satisfying sensory delight.",
        cite: "Sara Lin, Collection Archive Specialist"
      },
      specCard: {
        title: "Dragon Shield Matte Clear Sleeves",
        badge: "Curator's Standard",
        rating: "9.9",
        weight: "100 Microns (Heavy Duty)",
        players: "Standard European & Poker Sizes",
        time: "10+ Years Durability",
        mechanics: "Textured Matte Back, Non-Glare Front",
        pros: [
          "Zero glare under harsh overhead game store or living room lighting.",
          "Textured matte back prevents decks from sliding and collapsing across the table.",
          "Acid-free polypropylene prevents card ink transference over decades."
        ]
      },
      secondaryImages: [
        { src: "asstes/Cascadia Pacific Northwest Wonders.jpg", tag: "Tile Edge Preservation" },
        { src: "asstes/Mythic Prismatic Metal Polyhedral Dice Set.jpg", tag: "Dice Vault Foam Lining" }
      ],
      tactics: [
        { num: "01", title: "Choose 100-Micron Over 60-Micron", desc: "Penny sleeves (40-60 microns) crease easily and split at card corners. 100-micron premium sleeves withstand hundreds of aggressive riffle shuffles." },
        { num: "02", title: "Store Boxes Horizontally or Vertically?", desc: "Store heavy-box games vertically only when internal card trays have snap-tight lids. Otherwise, horizontal shelving prevents internal component shifting." },
        { num: "03", title: "Add Silica Gel Packs to RPG Boxes", desc: "Toss a rechargeable 10g food-safe silica gel packet inside campaign boxes like Frosthaven to prevent board warping in humid climates." },
        { num: "04", title: "Edge-Seal Your Cardboard Tokens", desc: "Use a clear acrylic lacquer pen around punchboard token edges to prevent cardboard delamination over years of play." }
      ],
      comments: [
        { name: "Michael Chang", badge: "Verified Buyer", date: "August 21, 2026 • 2:10 PM", stars: 5, text: "Switching from glossy to matte sleeves on Wingspan completely changed game nights. No more sliding bird decks!" },
        { name: "Sara Lin", badge: "Staff Curator", isStaff: true, date: "August 21, 2026 • 3:45 PM", text: "Glad to hear that, Michael! For Wingspan's 200+ cards, matte texture makes mash-shuffling effortless." },
        { name: "Elena R.", badge: "Lounge Member", date: "August 22, 2026 • 9:15 AM", stars: 5, text: "The silica gel tip saved my Gloomhaven tiles during Seattle rainy season. Must-read guide!" }
      ]
    },
    {
      id: "art-3",
      title: "How to Run Your Very First D&D Session as a New Dungeon Master",
      category: "Beginner Guides",
      date: "August 15, 2026",
      readTime: "8 Min Read",
      author: "Master Vance",
      authorRole: "Grand Campaign DM & Guildmaster · 15yr Veteran",
      authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
      authorBio: "Vance has DM'd over 350 public one-shots and multi-year campaigns. He trains new Dungeon Masters every month at Hobbix Tavern Nights.",
      authorFavs: "D&D 2024 • Call of Cthulhu • Frosthaven • Cyberpunk Red",
      image: "asstes/Dungeons & Dragons 2024 Player's Handbook.jpg",
      caption: "Preparing character sheets, initiative trackers, and miniature battlemaps with the D&D 2024 Player's Handbook.",
      excerpt: "Overcoming DM anxiety, designing low-stress starter encounters, pacing dialogue, and embracing player improvisation at the tabletop.",
      tags: ["DnD2024", "DMTips", "TabletopRPG", "Roleplaying"],
      featuredProducts: ["prod-7", "prod-8"],
      leadProse: "Stepping behind the Dungeon Master's screen for the very first time can feel intimidating. Between rules arbitrations, NPC voices, and combat calculations, new DMs often over-prepare intricate novels instead of creating fun play spaces. The secret to legendary sessions isn't memorizing all 400 pages of the rules—it is mastering momentum, player spotlighting, and collaborative storytelling.",
      pullQuote: {
        quote: "The DM isn't playing against the party—you are the cinematic lighting director, the orchestra conductor, and their biggest cheerleader when they roll that natural 20.",
        cite: "Master Vance, Tavern Guildmaster"
      },
      specCard: {
        title: "D&D 2024 Player's Handbook Core Rules",
        badge: "Essential Tome",
        rating: "9.95",
        weight: "Medium (Rules-Light Friendly)",
        players: "1 DM + 3–6 Adventurers",
        time: "180–240 Min per Session",
        mechanics: "d20 Skill Checks, Grid Combat, Narrative RP",
        pros: [
          "Overhauled weapon masteries give martial classes cinematic tactical combat options.",
          "Clearer spell formatting and unified terminology drastically reduce rules lookups at the table.",
          "Subclass features unlock earlier at Level 3, giving players immediate thematic identity."
        ]
      },
      secondaryImages: [
        { src: "asstes/Mythic Prismatic Metal Polyhedral Dice Set.jpg", tag: "Critical Hit Polyhedrals" },
        { src: "asstes/Arkham Horror The Living Card Game.jpg", tag: "Atmospheric Handouts" }
      ],
      tactics: [
        { num: "01", title: "Adopt the 'Five-Room Dungeon' Framework", desc: "Structure your first adventure into 5 simple beats: Entrance Guardian, Roleplay Puzzle, Trick/Trap, Boss Battle, and Revelatory Reward." },
        { num: "02", title: "Run a Structured Session Zero", desc: "Establish tone, safety tools, character connections, and table etiquette before rolling a single die to ensure all players align on the campaign vibe." },
        { num: "03", title: "When in Doubt, Ask for a DC 13 Check", desc: "Never stop game momentum searching through rulebooks for 10 minutes. Set an intuitive DC (10 easy, 15 medium, 20 hard) and adjudicate smoothly." },
        { num: "04", title: "Give Monsters Dynamic Goals Beyond Death", desc: "Goblins don't fight to the last breath; they flee, bargain, set ambushes, or sound alarms. Dynamic enemies make combat memorable." }
      ],
      comments: [
        { name: "Liam O.", badge: "New DM", date: "August 16, 2026 • 7:22 PM", stars: 5, text: "Used the 5-room dungeon template for my very first one-shot last Friday. My players had an absolute blast and asked to play weekly!" },
        { name: "Master Vance", badge: "Staff Curator", isStaff: true, date: "August 16, 2026 • 8:40 PM", text: "Congratulations on your first session, Liam! That first successful session is where lifelong gaming groups are born." },
        { name: "Hannah Briggs", badge: "Verified Buyer", date: "August 17, 2026 • 1:12 PM", stars: 5, text: "The weapon mastery tips for the 2024 edition made our barbarian feel like a superhero. Great writeup!" }
      ]
    },
    {
      id: "art-4",
      title: "2-Player Showdown: The 8 Best Cooperative Games for Couples",
      category: "Strategy Tips",
      date: "August 10, 2026",
      readTime: "6 Min Read",
      author: "Elena Rostova",
      authorRole: "Co-Op & Narrative Campaign Lead",
      authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
      authorBio: "Elena has tested over 300 two-player tabletop games. She curates the Hobbix Friday Couples Night and advises on low-conflict, high-synergy cooperative titles.",
      authorFavs: "Arkham Horror LCG • Cascadia • Codenames Duet • Spirit Island",
      image: "asstes/Cascadia Pacific Northwest Wonders.jpg",
      caption: "Building serene Pacific Northwest wildlife habitats in Cascadia during a 2-player evening session.",
      excerpt: "Skip the competitive arguments! Discover the most thrilling co-op puzzle and adventure board games tailored perfectly for intimate two-player game nights.",
      tags: ["2PlayerGames", "CoopBoardGames", "CouplesGameNight", "Cascadia"],
      featuredProducts: ["prod-6", "prod-2"],
      leadProse: "Finding the perfect 2-player board game can be a delicate balancing act. Highly competitive duels with direct take-that attacks can turn a relaxing evening into an argument. Cooperative board games channel all that brainpower toward a shared challenge, creating genuine camaraderie, nail-biting shared victories, and zero post-game resentment.",
      pullQuote: {
        quote: "The best two-player cooperative games don't just test your tactics—they teach you how your partner thinks, reacts under pressure, and celebrates shared triumph.",
        cite: "Elena Rostova, Co-Op Gaming Lead"
      },
      specCard: {
        title: "Cascadia: Pacific Northwest Wonders",
        badge: "Spiel des Jahres Winner",
        rating: "9.85",
        weight: "2.0 / 5.0 (Gateway / Relaxed)",
        players: "1–4 Players (Perfect at 2)",
        time: "30–45 Minutes",
        mechanics: "Tile Placement, Pattern Building, Solo / Duo Mode",
        pros: [
          "Zero downtime between turns—both players draft from the same dynamic market pool.",
          "Variable scoring cards ensure no two game setups ever play out identically.",
          "Calming nature theme with tactile wooden animal tokens and gorgeous pine cone markers."
        ]
      },
      secondaryImages: [
        { src: "asstes/Arkham Horror The Living Card Game.jpg", tag: "Narrative Campaign Co-Op" },
        { src: "asstes/Wingspan Master Collector's Edition.jpg", tag: "Parallel Engine Strategy" }
      ],
      tactics: [
        { num: "01", title: "Avoid the 'Quarterbacking' Trap", desc: "In co-op games, allow your partner to make their own choices even if sub-optimal. Discovery and experimentation are where the fun lives." },
        { num: "02", title: "Communicate Strategy, Not Commands", desc: "Phrase suggestions as questions: 'If you take that bear token now, what does your next turn look like?' rather than 'Take the bear.'" },
        { num: "03", title: "Scale Difficulty Incrementally", desc: "Start campaigns on standard difficulty to learn synergy combos before dialing up expert nightmare modes in games like Arkham Horror." },
        { num: "04", title: "Track Your Duo Win-Loss Chronicle", desc: "Keep a small journal in the game box recording dates, score tallies, and funny near-miss moments across your gaming journey." }
      ],
      comments: [
        { name: "Robert & Zoe", badge: "Verified Buyers", date: "August 11, 2026 • 9:40 PM", stars: 5, text: "Cascadia has become our nightly ritual before bed. Fast setup, beautiful artwork, and zero stress. 10/10 recommendation!" },
        { name: "Elena Rostova", badge: "Staff Curator", isStaff: true, date: "August 12, 2026 • 10:15 AM", text: "Love hearing that, Robert & Zoe! If you enjoy Cascadia, definitely look into Harmonies next for a vertical tile challenge." },
        { name: "Chloe M.", badge: "Lounge Member", date: "August 13, 2026 • 4:30 PM", stars: 5, text: "Arkham Horror LCG was intimidating at first, but playing duo investigator decks with my partner has been our favorite gaming experience ever." }
      ]
    },
    {
      id: "art-5",
      title: "Painting Your First Miniature: 5 Golden Rules for Smooth Basecoats",
      category: "Hobby Guides",
      date: "August 05, 2026",
      readTime: "9 Min Read",
      author: "Cole Harrison",
      authorRole: "Master Miniature Painter & Studio Artisan",
      authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
      authorBio: "Cole has painted miniatures professionally for 8 years, winning regional Golden Demon categories and hosting weekly painting clinics at Hobbix.",
      authorFavs: "Warhammer 40k • Marvel: Crisis Protocol • Frosthaven • Kingdom Death",
      image: "asstes/Mythic Prismatic Metal Polyhedral Dice Set.jpg",
      caption: "Fine-point synthetic sable brushes, acrylic wash palettes, and precision hobby craft at the Hobbix workshop.",
      excerpt: "Thin your paints with water or medium, use sable brushes properly, and avoid the dreaded clumpy primer trap with our step-by-step masterclass.",
      tags: ["MiniaturePainting", "HobbyCraft", "PaintingGuide", "Warhammer"],
      featuredProducts: ["prod-8", "prod-7"],
      leadProse: "Opening a box of grey plastic miniatures and transforming them into vibrant, tabletop-ready heroes is one of the most rewarding hobbies in gaming. Yet many beginners get discouraged early by chalky basecoats, flooded details from heavy washes, or paint drying too fast on the brush. The difference between a muddy mini and a crisp display model comes down to water control, brush angle, and thin layers.",
      pullQuote: {
        quote: "Two thin coats will always triumph over one thick coat. Patience and water control reveal every sculpted muscle, rivet, and fold of cloth.",
        cite: "Cole Harrison, Studio Miniature Painter"
      },
      specCard: {
        title: "Kolinsky Sable Detail Brush Set & Wet Palette",
        badge: "Artisan Standard",
        rating: "9.9",
        weight: "Precision Grade (Size 00, 0, 1, 2)",
        players: "Solo Hobbyist Craft",
        time: "15–45 Min per Miniature",
        mechanics: "Capillary Paint Flow, Snap Tip Retention",
        pros: [
          "Natural sable bristles maintain a razor-sharp point through hundreds of painting sessions.",
          "Wet palette hydro-sponge keeps acrylics workable for days without skinning over.",
          "Ergonomic triangular handles reduce hand fatigue during intricate detailing."
        ]
      },
      secondaryImages: [
        { src: "asstes/Dungeons & Dragons 2024 Player's Handbook.jpg", tag: "Miniature Lore Inspiration" },
        { src: "asstes/Secret Hitler Deluxe Wooden Box Edition.jpg", tag: "Tactile Craft Materials" }
      ],
      tactics: [
        { num: "01", title: "Always Thin Paint to Skim-Milk Consistency", desc: "Never apply paint directly from the pot. Add 2 drops of water or acrylic medium until the paint flows effortlessly off the brush without beading." },
        { num: "02", title: "Use Zenithal Highlighting with Primer", desc: "Prime your miniature in black, then spray white primer at a 45-degree angle from above to naturally map shadows and highlight zones." },
        { num: "03", title: "Wick Excess Wash on Paper Towel", desc: "Before applying a shade or wash, touch the brush tip to a paper towel. This prevents pooling and ugly coffee-stain rings on flat armor panels." },
        { num: "04", title: "Keep Brush Ferrule Free of Dried Paint", desc: "Never submerge your brush deeper than halfway up the bristles. Dried paint in the metal ferrule splays the tip and destroys precision." }
      ],
      comments: [
        { name: "Tyler B.", badge: "Verified Buyer", date: "August 06, 2026 • 5:18 PM", stars: 5, text: "The skim-milk consistency advice finally fixed my chalky space marines. My basecoats are actually smooth now!" },
        { name: "Cole Harrison", badge: "Staff Curator", isStaff: true, date: "August 06, 2026 • 6:30 PM", text: "That is the single biggest breakthrough for any painter, Tyler! Keep your coats thin and let each layer dry completely." },
        { name: "Marcus P.", badge: "Lounge Member", date: "August 07, 2026 • 11:45 AM", stars: 5, text: "Attended Cole's clinic in Seattle last week and bought the wet palette. My paints stayed wet for 3 days straight!" }
      ]
    },
    {
      id: "art-6",
      title: "Social Deduction Secrets: How to Win as the Traitor in Hidden Role Games",
      category: "Strategy Tips",
      date: "July 28, 2026",
      readTime: "6 Min Read",
      author: "Julian Thorne",
      authorRole: "Competitive Tabletop Strategist",
      authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
      authorBio: "Julian has competed in regional social deduction tournaments across the Pacific Northwest. He specializes in behavioral profiling, deception detection, and chaos theory.",
      authorFavs: "Secret Hitler • Blood on the Clocktower • Avalon • Dune: Imperium",
      image: "asstes/Secret Hitler Deluxe Wooden Box Edition.jpg",
      caption: "Secret policy enactments, wooden ballot placards, and tense political bluffing in Secret Hitler Deluxe Edition.",
      excerpt: "Psychological framing, subtle deflection techniques, and timing your power plays in Secret Hitler, Blood on the Clocktower, and Avalon.",
      tags: ["SecretHitler", "SocialDeduction", "BluffingStrategy", "PartyGames"],
      featuredProducts: ["prod-4", "prod-10"],
      leadProse: "In games of hidden roles and social deduction, the real board isn't the wooden track or card deck—it is the psychology of the human beings sitting around the table. Playing as the informed minority (the traitors, fascists, or evil minions) requires an entirely different skill set than traditional Euro strategy. You must project calm rationality, build trust with unsuspecting loyalists, and sow confusion at the exact pivotal moment.",
      pullQuote: {
        quote: "The greatest deception in social deduction isn't telling a convincing lie—it is telling 90% truth and letting your opponents draw the wrong conclusion themselves.",
        cite: "Julian Thorne, Strategy Curator"
      },
      specCard: {
        title: "Secret Hitler Deluxe Wooden Box Edition",
        badge: "Party Game Masterpiece",
        rating: "9.9",
        weight: "2.3 / 5.0 (High Social Heat)",
        players: "5–10 Players (Best at 7-8)",
        time: "45–60 Minutes",
        mechanics: "Hidden Roles, Voting, Secret Policy Drafting",
        pros: [
          "Solid wood policy placards and foil embossed secret envelopes provide heirloom table presence.",
          "Strict no-table-talk rules during legislative drafting maintain thrilling poker tension.",
          "Scales dynamically as fascist victory track unlocks execution powers for the President."
        ]
      },
      secondaryImages: [
        { src: "asstes/Dune Imperium – Uprising.jpg", tag: "Political Betrayal Intrigue" },
        { src: "asstes/Arkham Horror The Living Card Game.jpg", tag: "Hidden Motive Cards" }
      ],
      tactics: [
        { num: "01", title: "Never Defend Yourself Too Eagerly", desc: "Innocent players don't panic when accused because they know they are good. When accused, shrug, state facts calmly, and ask questions back." },
        { num: "02", title: "Adopt an Ally Early and Protect Them", desc: "Pick one vocal good player in Round 1 and consistently agree with their logic. When the end-game arrives, they will fiercely defend your innocence." },
        { num: "03", title: "Create Conflicting Narratives, Not Silence", desc: "Passive traitors always lose. Generate plausible alternative theories for why bad policies were enacted to divide good-player votes." },
        { num: "04", title: "Time Your Reveal for Maximum Shock", desc: "Hold your true identity until the math makes victory mathematically guaranteed. Early reveals unite the table against you." }
      ],
      comments: [
        { name: "Gabriel S.", badge: "Verified Buyer", date: "July 29, 2026 • 8:15 PM", stars: 5, text: "The tip about adopting an ally early won our 8-player Secret Hitler game last night. The table was completely stunned at the reveal!" },
        { name: "Julian Thorne", badge: "Staff Curator", isStaff: true, date: "July 29, 2026 • 9:30 PM", text: "Haha! That is the hallmark of a master traitor game, Gabriel. When your strongest defender was actually helping you win all along!" },
        { name: "Devon K.", badge: "Lounge Member", date: "July 30, 2026 • 1:40 PM", stars: 5, text: "The wooden box edition from Hobbix is breathtaking. Premium components elevate the whole evening." }
      ]
    }
  ]
};
